font_family JetBrainsMono Nerd Font
font_size 11.0

hide_window_decorations yes

background #0a0f1a
foreground #cdd6f4

cursor #c792ea

enable_audio_bell no

# TRANSPARENCIA REAL
background_opacity 0.70

linux_display_server=auto
enable_audio_bell no
shell_integration no
