[colors]
green = #54b8f2
white = #FFFFFF
bg = #cc000000

# BAR
[bar/main]
width = 100%
height = 36
background = ${colors.bg}
foreground = ${colors.green}
border-size = 2
border-color = #0f364c
padding-left = 2
padding-right = 2
module-margin = 3
modules-left = cpu temperature memory
modules-center = workspaces
modules-right = network spotify volume battery date
font-0 = "JetBrainsMono Nerd Font:size=13"
enable-ipc = true

# WORKSPACES
[module/workspaces]
type = internal/i3
pin-workspaces = true
index-sort = true

label-focused = %name%
label-unfocused = %name%
label-visible = %name%

label-focused-font = 2
label-unfocused-font = 2
label-visible-font = 2

label-focused-padding = 2
label-unfocused-padding = 2
label-visible-padding = 2

label-focused-background = #0f364c
label-focused-foreground = #54b8f2
label-unfocused-foreground = #888888

# NETWORK
[module/network]
type = custom/script
exec = ~/.config/polybar/scripts/network.sh
interval = 3
label = %output%

# CPU
[module/cpu]
type = internal/cpu
interval = 2
format = <label>
label =  %percentage%%

# TEMPERATURE
[module/temperature]
type = internal/temperature
interval = 2
thermal-zone = 0
warn-temperature = 75
format = <label>
label =  %temperature-c%

# MEMORY
[module/memory]
type = internal/memory
interval = 2
format = <label>
label =  %percentage_used%%

# SPOTIFY
[module/spotify]
type = custom/script
exec = ~/.config/polybar/scripts/spotify.sh
interval = 2
label = %output%

# VOLUME
[module/volume]
[module/volume]
type = custom/script
exec = ~/.config/polybar/scripts/volume.sh
interval = 1
click-left = ~/.config/polybar/scripts/volume_slider.sh
scroll-up = ~/.config/polybar/scripts/volume.sh up
scroll-down = ~/.config/polybar/scripts/volume.sh down
label = %output%

# BATTERY
[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
format-discharging = <label>
label = 🔋 %percentage%%

# DATE
[module/date]
type = internal/date
interval = 5
date = %d/%m
time = %H:%M
label = %date% %time%
